[workspace]
resolver = "3"
members = [
    "./agent-k",
    "./backend",
    "./docling-sys",
    "./workspace",
]
exclude = [
    "./backend-v1",
]

[workspace.dependencies]
agent-k = { path = "./agent-k" }
ailoy = { git = "https://github.com/brekkylab/ailoy.git", rev = "43d2a8227f53118137f3319094398549f465275f", features = ["sandbox"] }
