/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsProjectSlugRouteImport } from './routes/_app.projects.$projectSlug'
import { Route as AppProjectsProjectSlugIndexRouteImport } from './routes/_app.projects.$projectSlug.index'
import { Route as AppProjectsProjectSlugSkillsRouteImport } from './routes/_app.projects.$projectSlug.skills'
import { Route as AppProjectsProjectSlugSettingsRouteImport } from './routes/_app.projects.$projectSlug.settings'
import { Route as AppProjectsProjectSlugScheduleRouteImport } from './routes/_app.projects.$projectSlug.schedule'
import { Route as AppProjectsProjectSlugMembersRouteImport } from './routes/_app.projects.$projectSlug.members'
import { Route as AppProjectsProjectSlugFilesRouteImport } from './routes/_app.projects.$projectSlug.files'
import { Route as AppProjectsProjectIdAutomationRouteImport } from './routes/_app.projects.$projectId.automation'
import { Route as AppProjectsProjectIdAutomationIndexRouteImport } from './routes/_app.projects.$projectId.automation.index'
import { Route as AppProjectsProjectSlugSessionsSessionPrefixRouteImport } from './routes/_app.projects.$projectSlug.sessions.$sessionPrefix'
import { Route as AppProjectsProjectIdAutomationNewRouteImport } from './routes/_app.projects.$projectId.automation.new'
import { Route as AppProjectsProjectIdAutomationAutomationIdRouteImport } from './routes/_app.projects.$projectId.automation.$automationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectSlugRoute = AppProjectsProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectSlugIndexRoute =
  AppProjectsProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugSkillsRoute =
  AppProjectsProjectSlugSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugSettingsRoute =
  AppProjectsProjectSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugScheduleRoute =
  AppProjectsProjectSlugScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugMembersRoute =
  AppProjectsProjectSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugFilesRoute =
  AppProjectsProjectSlugFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectIdAutomationRoute =
  AppProjectsProjectIdAutomationRouteImport.update({
    id: '/$projectId/automation',
    path: '/$projectId/automation',
    getParentRoute: () => AppProjectsRoute,
  } as any)
const AppProjectsProjectIdAutomationIndexRoute =
  AppProjectsProjectIdAutomationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdAutomationRoute,
  } as any)
const AppProjectsProjectSlugSessionsSessionPrefixRoute =
  AppProjectsProjectSlugSessionsSessionPrefixRouteImport.update({
    id: '/sessions/$sessionPrefix',
    path: '/sessions/$sessionPrefix',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectIdAutomationNewRoute =
  AppProjectsProjectIdAutomationNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppProjectsProjectIdAutomationRoute,
  } as any)
const AppProjectsProjectIdAutomationAutomationIdRoute =
  AppProjectsProjectIdAutomationAutomationIdRouteImport.update({
    id: '/$automationId',
    path: '/$automationId',
    getParentRoute: () => AppProjectsProjectIdAutomationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/projects/$projectSlug': typeof AppProjectsProjectSlugRouteWithChildren
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectId/automation': typeof AppProjectsProjectIdAutomationRouteWithChildren
  '/projects/$projectSlug/files': typeof AppProjectsProjectSlugFilesRoute
  '/projects/$projectSlug/members': typeof AppProjectsProjectSlugMembersRoute
  '/projects/$projectSlug/schedule': typeof AppProjectsProjectSlugScheduleRoute
  '/projects/$projectSlug/settings': typeof AppProjectsProjectSlugSettingsRoute
  '/projects/$projectSlug/skills': typeof AppProjectsProjectSlugSkillsRoute
  '/projects/$projectSlug/': typeof AppProjectsProjectSlugIndexRoute
  '/projects/$projectId/automation/$automationId': typeof AppProjectsProjectIdAutomationAutomationIdRoute
  '/projects/$projectId/automation/new': typeof AppProjectsProjectIdAutomationNewRoute
  '/projects/$projectSlug/sessions/$sessionPrefix': typeof AppProjectsProjectSlugSessionsSessionPrefixRoute
  '/projects/$projectId/automation/': typeof AppProjectsProjectIdAutomationIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectSlug/files': typeof AppProjectsProjectSlugFilesRoute
  '/projects/$projectSlug/members': typeof AppProjectsProjectSlugMembersRoute
  '/projects/$projectSlug/schedule': typeof AppProjectsProjectSlugScheduleRoute
  '/projects/$projectSlug/settings': typeof AppProjectsProjectSlugSettingsRoute
  '/projects/$projectSlug/skills': typeof AppProjectsProjectSlugSkillsRoute
  '/projects/$projectSlug': typeof AppProjectsProjectSlugIndexRoute
  '/projects/$projectId/automation/$automationId': typeof AppProjectsProjectIdAutomationAutomationIdRoute
  '/projects/$projectId/automation/new': typeof AppProjectsProjectIdAutomationNewRoute
  '/projects/$projectSlug/sessions/$sessionPrefix': typeof AppProjectsProjectSlugSessionsSessionPrefixRoute
  '/projects/$projectId/automation': typeof AppProjectsProjectIdAutomationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$projectSlug': typeof AppProjectsProjectSlugRouteWithChildren
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectId/automation': typeof AppProjectsProjectIdAutomationRouteWithChildren
  '/_app/projects/$projectSlug/files': typeof AppProjectsProjectSlugFilesRoute
  '/_app/projects/$projectSlug/members': typeof AppProjectsProjectSlugMembersRoute
  '/_app/projects/$projectSlug/schedule': typeof AppProjectsProjectSlugScheduleRoute
  '/_app/projects/$projectSlug/settings': typeof AppProjectsProjectSlugSettingsRoute
  '/_app/projects/$projectSlug/skills': typeof AppProjectsProjectSlugSkillsRoute
  '/_app/projects/$projectSlug/': typeof AppProjectsProjectSlugIndexRoute
  '/_app/projects/$projectId/automation/$automationId': typeof AppProjectsProjectIdAutomationAutomationIdRoute
  '/_app/projects/$projectId/automation/new': typeof AppProjectsProjectIdAutomationNewRoute
  '/_app/projects/$projectSlug/sessions/$sessionPrefix': typeof AppProjectsProjectSlugSessionsSessionPrefixRoute
  '/_app/projects/$projectId/automation/': typeof AppProjectsProjectIdAutomationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects'
    | '/projects/$projectSlug'
    | '/projects/'
    | '/projects/$projectId/automation'
    | '/projects/$projectSlug/files'
    | '/projects/$projectSlug/members'
    | '/projects/$projectSlug/schedule'
    | '/projects/$projectSlug/settings'
    | '/projects/$projectSlug/skills'
    | '/projects/$projectSlug/'
    | '/projects/$projectId/automation/$automationId'
    | '/projects/$projectId/automation/new'
    | '/projects/$projectSlug/sessions/$sessionPrefix'
    | '/projects/$projectId/automation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/projects'
    | '/projects/$projectSlug/files'
    | '/projects/$projectSlug/members'
    | '/projects/$projectSlug/schedule'
    | '/projects/$projectSlug/settings'
    | '/projects/$projectSlug/skills'
    | '/projects/$projectSlug'
    | '/projects/$projectId/automation/$automationId'
    | '/projects/$projectId/automation/new'
    | '/projects/$projectSlug/sessions/$sessionPrefix'
    | '/projects/$projectId/automation'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/projects'
    | '/_app/'
    | '/_app/projects/$projectSlug'
    | '/_app/projects/'
    | '/_app/projects/$projectId/automation'
    | '/_app/projects/$projectSlug/files'
    | '/_app/projects/$projectSlug/members'
    | '/_app/projects/$projectSlug/schedule'
    | '/_app/projects/$projectSlug/settings'
    | '/_app/projects/$projectSlug/skills'
    | '/_app/projects/$projectSlug/'
    | '/_app/projects/$projectId/automation/$automationId'
    | '/_app/projects/$projectId/automation/new'
    | '/_app/projects/$projectSlug/sessions/$sessionPrefix'
    | '/_app/projects/$projectId/automation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectSlug': {
      id: '/_app/projects/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof AppProjectsProjectSlugRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectSlug/': {
      id: '/_app/projects/$projectSlug/'
      path: '/'
      fullPath: '/projects/$projectSlug/'
      preLoaderRoute: typeof AppProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectSlug/skills': {
      id: '/_app/projects/$projectSlug/skills'
      path: '/skills'
      fullPath: '/projects/$projectSlug/skills'
      preLoaderRoute: typeof AppProjectsProjectSlugSkillsRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectSlug/settings': {
      id: '/_app/projects/$projectSlug/settings'
      path: '/settings'
      fullPath: '/projects/$projectSlug/settings'
      preLoaderRoute: typeof AppProjectsProjectSlugSettingsRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectSlug/schedule': {
      id: '/_app/projects/$projectSlug/schedule'
      path: '/schedule'
      fullPath: '/projects/$projectSlug/schedule'
      preLoaderRoute: typeof AppProjectsProjectSlugScheduleRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectSlug/members': {
      id: '/_app/projects/$projectSlug/members'
      path: '/members'
      fullPath: '/projects/$projectSlug/members'
      preLoaderRoute: typeof AppProjectsProjectSlugMembersRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectSlug/files': {
      id: '/_app/projects/$projectSlug/files'
      path: '/files'
      fullPath: '/projects/$projectSlug/files'
      preLoaderRoute: typeof AppProjectsProjectSlugFilesRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectId/automation': {
      id: '/_app/projects/$projectId/automation'
      path: '/$projectId/automation'
      fullPath: '/projects/$projectId/automation'
      preLoaderRoute: typeof AppProjectsProjectIdAutomationRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId/automation/': {
      id: '/_app/projects/$projectId/automation/'
      path: '/'
      fullPath: '/projects/$projectId/automation/'
      preLoaderRoute: typeof AppProjectsProjectIdAutomationIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdAutomationRoute
    }
    '/_app/projects/$projectSlug/sessions/$sessionPrefix': {
      id: '/_app/projects/$projectSlug/sessions/$sessionPrefix'
      path: '/sessions/$sessionPrefix'
      fullPath: '/projects/$projectSlug/sessions/$sessionPrefix'
      preLoaderRoute: typeof AppProjectsProjectSlugSessionsSessionPrefixRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectId/automation/new': {
      id: '/_app/projects/$projectId/automation/new'
      path: '/new'
      fullPath: '/projects/$projectId/automation/new'
      preLoaderRoute: typeof AppProjectsProjectIdAutomationNewRouteImport
      parentRoute: typeof AppProjectsProjectIdAutomationRoute
    }
    '/_app/projects/$projectId/automation/$automationId': {
      id: '/_app/projects/$projectId/automation/$automationId'
      path: '/$automationId'
      fullPath: '/projects/$projectId/automation/$automationId'
      preLoaderRoute: typeof AppProjectsProjectIdAutomationAutomationIdRouteImport
      parentRoute: typeof AppProjectsProjectIdAutomationRoute
    }
  }
}

interface AppProjectsProjectSlugRouteChildren {
  AppProjectsProjectSlugFilesRoute: typeof AppProjectsProjectSlugFilesRoute
  AppProjectsProjectSlugMembersRoute: typeof AppProjectsProjectSlugMembersRoute
  AppProjectsProjectSlugScheduleRoute: typeof AppProjectsProjectSlugScheduleRoute
  AppProjectsProjectSlugSettingsRoute: typeof AppProjectsProjectSlugSettingsRoute
  AppProjectsProjectSlugSkillsRoute: typeof AppProjectsProjectSlugSkillsRoute
  AppProjectsProjectSlugIndexRoute: typeof AppProjectsProjectSlugIndexRoute
  AppProjectsProjectSlugSessionsSessionPrefixRoute: typeof AppProjectsProjectSlugSessionsSessionPrefixRoute
}

const AppProjectsProjectSlugRouteChildren: AppProjectsProjectSlugRouteChildren =
  {
    AppProjectsProjectSlugFilesRoute: AppProjectsProjectSlugFilesRoute,
    AppProjectsProjectSlugMembersRoute: AppProjectsProjectSlugMembersRoute,
    AppProjectsProjectSlugScheduleRoute: AppProjectsProjectSlugScheduleRoute,
    AppProjectsProjectSlugSettingsRoute: AppProjectsProjectSlugSettingsRoute,
    AppProjectsProjectSlugSkillsRoute: AppProjectsProjectSlugSkillsRoute,
    AppProjectsProjectSlugIndexRoute: AppProjectsProjectSlugIndexRoute,
    AppProjectsProjectSlugSessionsSessionPrefixRoute:
      AppProjectsProjectSlugSessionsSessionPrefixRoute,
  }

const AppProjectsProjectSlugRouteWithChildren =
  AppProjectsProjectSlugRoute._addFileChildren(
    AppProjectsProjectSlugRouteChildren,
  )

interface AppProjectsProjectIdAutomationRouteChildren {
  AppProjectsProjectIdAutomationAutomationIdRoute: typeof AppProjectsProjectIdAutomationAutomationIdRoute
  AppProjectsProjectIdAutomationNewRoute: typeof AppProjectsProjectIdAutomationNewRoute
  AppProjectsProjectIdAutomationIndexRoute: typeof AppProjectsProjectIdAutomationIndexRoute
}

const AppProjectsProjectIdAutomationRouteChildren: AppProjectsProjectIdAutomationRouteChildren =
  {
    AppProjectsProjectIdAutomationAutomationIdRoute:
      AppProjectsProjectIdAutomationAutomationIdRoute,
    AppProjectsProjectIdAutomationNewRoute:
      AppProjectsProjectIdAutomationNewRoute,
    AppProjectsProjectIdAutomationIndexRoute:
      AppProjectsProjectIdAutomationIndexRoute,
  }

const AppProjectsProjectIdAutomationRouteWithChildren =
  AppProjectsProjectIdAutomationRoute._addFileChildren(
    AppProjectsProjectIdAutomationRouteChildren,
  )

interface AppProjectsRouteChildren {
  AppProjectsProjectSlugRoute: typeof AppProjectsProjectSlugRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdAutomationRoute: typeof AppProjectsProjectIdAutomationRouteWithChildren
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectSlugRoute: AppProjectsProjectSlugRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdAutomationRoute:
    AppProjectsProjectIdAutomationRouteWithChildren,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
