/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsProjectSlugRouteImport } from './routes/_app.projects.$projectSlug'
import { Route as AppProjectsProjectSlugIndexRouteImport } from './routes/_app.projects.$projectSlug.index'
import { Route as AppProjectsProjectSlugSettingsRouteImport } from './routes/_app.projects.$projectSlug.settings'
import { Route as AppProjectsProjectSlugMembersRouteImport } from './routes/_app.projects.$projectSlug.members'
import { Route as AppProjectsProjectSlugFilesRouteImport } from './routes/_app.projects.$projectSlug.files'
import { Route as AppProjectsProjectSlugAutomationRouteImport } from './routes/_app.projects.$projectSlug.automation'
import { Route as AppProjectsProjectSlugAutomationIndexRouteImport } from './routes/_app.projects.$projectSlug.automation.index'
import { Route as AppProjectsProjectSlugSessionsSessionPrefixRouteImport } from './routes/_app.projects.$projectSlug.sessions.$sessionPrefix'
import { Route as AppProjectsProjectSlugAutomationNewRouteImport } from './routes/_app.projects.$projectSlug.automation.new'
import { Route as AppProjectsProjectSlugAutomationAutomationIdRouteImport } from './routes/_app.projects.$projectSlug.automation.$automationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectSlugRoute = AppProjectsProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectSlugIndexRoute =
  AppProjectsProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugSettingsRoute =
  AppProjectsProjectSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugMembersRoute =
  AppProjectsProjectSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugFilesRoute =
  AppProjectsProjectSlugFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugAutomationRoute =
  AppProjectsProjectSlugAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugAutomationIndexRoute =
  AppProjectsProjectSlugAutomationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectSlugAutomationRoute,
  } as any)
const AppProjectsProjectSlugSessionsSessionPrefixRoute =
  AppProjectsProjectSlugSessionsSessionPrefixRouteImport.update({
    id: '/sessions/$sessionPrefix',
    path: '/sessions/$sessionPrefix',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugAutomationNewRoute =
  AppProjectsProjectSlugAutomationNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppProjectsProjectSlugAutomationRoute,
  } as any)
const AppProjectsProjectSlugAutomationAutomationIdRoute =
  AppProjectsProjectSlugAutomationAutomationIdRouteImport.update({
    id: '/$automationId',
    path: '/$automationId',
    getParentRoute: () => AppProjectsProjectSlugAutomationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/projects/$projectSlug': typeof AppProjectsProjectSlugRouteWithChildren
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectSlug/automation': typeof AppProjectsProjectSlugAutomationRouteWithChildren
  '/projects/$projectSlug/files': typeof AppProjectsProjectSlugFilesRoute
  '/projects/$projectSlug/members': typeof AppProjectsProjectSlugMembersRoute
  '/projects/$projectSlug/settings': typeof AppProjectsProjectSlugSettingsRoute
  '/projects/$projectSlug/': typeof AppProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/automation/$automationId': typeof AppProjectsProjectSlugAutomationAutomationIdRoute
  '/projects/$projectSlug/automation/new': typeof AppProjectsProjectSlugAutomationNewRoute
  '/projects/$projectSlug/sessions/$sessionPrefix': typeof AppProjectsProjectSlugSessionsSessionPrefixRoute
  '/projects/$projectSlug/automation/': typeof AppProjectsProjectSlugAutomationIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectSlug/files': typeof AppProjectsProjectSlugFilesRoute
  '/projects/$projectSlug/members': typeof AppProjectsProjectSlugMembersRoute
  '/projects/$projectSlug/settings': typeof AppProjectsProjectSlugSettingsRoute
  '/projects/$projectSlug': typeof AppProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/automation/$automationId': typeof AppProjectsProjectSlugAutomationAutomationIdRoute
  '/projects/$projectSlug/automation/new': typeof AppProjectsProjectSlugAutomationNewRoute
  '/projects/$projectSlug/sessions/$sessionPrefix': typeof AppProjectsProjectSlugSessionsSessionPrefixRoute
  '/projects/$projectSlug/automation': typeof AppProjectsProjectSlugAutomationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$projectSlug': typeof AppProjectsProjectSlugRouteWithChildren
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectSlug/automation': typeof AppProjectsProjectSlugAutomationRouteWithChildren
  '/_app/projects/$projectSlug/files': typeof AppProjectsProjectSlugFilesRoute
  '/_app/projects/$projectSlug/members': typeof AppProjectsProjectSlugMembersRoute
  '/_app/projects/$projectSlug/settings': typeof AppProjectsProjectSlugSettingsRoute
  '/_app/projects/$projectSlug/': typeof AppProjectsProjectSlugIndexRoute
  '/_app/projects/$projectSlug/automation/$automationId': typeof AppProjectsProjectSlugAutomationAutomationIdRoute
  '/_app/projects/$projectSlug/automation/new': typeof AppProjectsProjectSlugAutomationNewRoute
  '/_app/projects/$projectSlug/sessions/$sessionPrefix': typeof AppProjectsProjectSlugSessionsSessionPrefixRoute
  '/_app/projects/$projectSlug/automation/': typeof AppProjectsProjectSlugAutomationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects'
    | '/projects/$projectSlug'
    | '/projects/'
    | '/projects/$projectSlug/automation'
    | '/projects/$projectSlug/files'
    | '/projects/$projectSlug/members'
    | '/projects/$projectSlug/settings'
    | '/projects/$projectSlug/'
    | '/projects/$projectSlug/automation/$automationId'
    | '/projects/$projectSlug/automation/new'
    | '/projects/$projectSlug/sessions/$sessionPrefix'
    | '/projects/$projectSlug/automation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/projects'
    | '/projects/$projectSlug/files'
    | '/projects/$projectSlug/members'
    | '/projects/$projectSlug/settings'
    | '/projects/$projectSlug'
    | '/projects/$projectSlug/automation/$automationId'
    | '/projects/$projectSlug/automation/new'
    | '/projects/$projectSlug/sessions/$sessionPrefix'
    | '/projects/$projectSlug/automation'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/projects'
    | '/_app/'
    | '/_app/projects/$projectSlug'
    | '/_app/projects/'
    | '/_app/projects/$projectSlug/automation'
    | '/_app/projects/$projectSlug/files'
    | '/_app/projects/$projectSlug/members'
    | '/_app/projects/$projectSlug/settings'
    | '/_app/projects/$projectSlug/'
    | '/_app/projects/$projectSlug/automation/$automationId'
    | '/_app/projects/$projectSlug/automation/new'
    | '/_app/projects/$projectSlug/sessions/$sessionPrefix'
    | '/_app/projects/$projectSlug/automation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectSlug': {
      id: '/_app/projects/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof AppProjectsProjectSlugRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectSlug/': {
      id: '/_app/projects/$projectSlug/'
      path: '/'
      fullPath: '/projects/$projectSlug/'
      preLoaderRoute: typeof AppProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectSlug/settings': {
      id: '/_app/projects/$projectSlug/settings'
      path: '/settings'
      fullPath: '/projects/$projectSlug/settings'
      preLoaderRoute: typeof AppProjectsProjectSlugSettingsRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectSlug/members': {
      id: '/_app/projects/$projectSlug/members'
      path: '/members'
      fullPath: '/projects/$projectSlug/members'
      preLoaderRoute: typeof AppProjectsProjectSlugMembersRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectSlug/files': {
      id: '/_app/projects/$projectSlug/files'
      path: '/files'
      fullPath: '/projects/$projectSlug/files'
      preLoaderRoute: typeof AppProjectsProjectSlugFilesRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectSlug/automation': {
      id: '/_app/projects/$projectSlug/automation'
      path: '/automation'
      fullPath: '/projects/$projectSlug/automation'
      preLoaderRoute: typeof AppProjectsProjectSlugAutomationRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectSlug/automation/': {
      id: '/_app/projects/$projectSlug/automation/'
      path: '/'
      fullPath: '/projects/$projectSlug/automation/'
      preLoaderRoute: typeof AppProjectsProjectSlugAutomationIndexRouteImport
      parentRoute: typeof AppProjectsProjectSlugAutomationRoute
    }
    '/_app/projects/$projectSlug/sessions/$sessionPrefix': {
      id: '/_app/projects/$projectSlug/sessions/$sessionPrefix'
      path: '/sessions/$sessionPrefix'
      fullPath: '/projects/$projectSlug/sessions/$sessionPrefix'
      preLoaderRoute: typeof AppProjectsProjectSlugSessionsSessionPrefixRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    '/_app/projects/$projectSlug/automation/new': {
      id: '/_app/projects/$projectSlug/automation/new'
      path: '/new'
      fullPath: '/projects/$projectSlug/automation/new'
      preLoaderRoute: typeof AppProjectsProjectSlugAutomationNewRouteImport
      parentRoute: typeof AppProjectsProjectSlugAutomationRoute
    }
    '/_app/projects/$projectSlug/automation/$automationId': {
      id: '/_app/projects/$projectSlug/automation/$automationId'
      path: '/$automationId'
      fullPath: '/projects/$projectSlug/automation/$automationId'
      preLoaderRoute: typeof AppProjectsProjectSlugAutomationAutomationIdRouteImport
      parentRoute: typeof AppProjectsProjectSlugAutomationRoute
    }
  }
}

interface AppProjectsProjectSlugAutomationRouteChildren {
  AppProjectsProjectSlugAutomationAutomationIdRoute: typeof AppProjectsProjectSlugAutomationAutomationIdRoute
  AppProjectsProjectSlugAutomationNewRoute: typeof AppProjectsProjectSlugAutomationNewRoute
  AppProjectsProjectSlugAutomationIndexRoute: typeof AppProjectsProjectSlugAutomationIndexRoute
}

const AppProjectsProjectSlugAutomationRouteChildren: AppProjectsProjectSlugAutomationRouteChildren =
  {
    AppProjectsProjectSlugAutomationAutomationIdRoute:
      AppProjectsProjectSlugAutomationAutomationIdRoute,
    AppProjectsProjectSlugAutomationNewRoute:
      AppProjectsProjectSlugAutomationNewRoute,
    AppProjectsProjectSlugAutomationIndexRoute:
      AppProjectsProjectSlugAutomationIndexRoute,
  }

const AppProjectsProjectSlugAutomationRouteWithChildren =
  AppProjectsProjectSlugAutomationRoute._addFileChildren(
    AppProjectsProjectSlugAutomationRouteChildren,
  )

interface AppProjectsProjectSlugRouteChildren {
  AppProjectsProjectSlugAutomationRoute: typeof AppProjectsProjectSlugAutomationRouteWithChildren
  AppProjectsProjectSlugFilesRoute: typeof AppProjectsProjectSlugFilesRoute
  AppProjectsProjectSlugMembersRoute: typeof AppProjectsProjectSlugMembersRoute
  AppProjectsProjectSlugSettingsRoute: typeof AppProjectsProjectSlugSettingsRoute
  AppProjectsProjectSlugIndexRoute: typeof AppProjectsProjectSlugIndexRoute
  AppProjectsProjectSlugSessionsSessionPrefixRoute: typeof AppProjectsProjectSlugSessionsSessionPrefixRoute
}

const AppProjectsProjectSlugRouteChildren: AppProjectsProjectSlugRouteChildren =
  {
    AppProjectsProjectSlugAutomationRoute:
      AppProjectsProjectSlugAutomationRouteWithChildren,
    AppProjectsProjectSlugFilesRoute: AppProjectsProjectSlugFilesRoute,
    AppProjectsProjectSlugMembersRoute: AppProjectsProjectSlugMembersRoute,
    AppProjectsProjectSlugSettingsRoute: AppProjectsProjectSlugSettingsRoute,
    AppProjectsProjectSlugIndexRoute: AppProjectsProjectSlugIndexRoute,
    AppProjectsProjectSlugSessionsSessionPrefixRoute:
      AppProjectsProjectSlugSessionsSessionPrefixRoute,
  }

const AppProjectsProjectSlugRouteWithChildren =
  AppProjectsProjectSlugRoute._addFileChildren(
    AppProjectsProjectSlugRouteChildren,
  )

interface AppProjectsRouteChildren {
  AppProjectsProjectSlugRoute: typeof AppProjectsProjectSlugRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectSlugRoute: AppProjectsProjectSlugRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
