/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPRouteImport } from './routes/_app.p'
import { Route as AppPIndexRouteImport } from './routes/_app.p.index'
import { Route as AppPProjectSlugRouteImport } from './routes/_app.p.$projectSlug'
import { Route as AppPProjectSlugIndexRouteImport } from './routes/_app.p.$projectSlug.index'
import { Route as AppPProjectSlugSkillsRouteImport } from './routes/_app.p.$projectSlug.skills'
import { Route as AppPProjectSlugSettingsRouteImport } from './routes/_app.p.$projectSlug.settings'
import { Route as AppPProjectSlugScheduleRouteImport } from './routes/_app.p.$projectSlug.schedule'
import { Route as AppPProjectSlugMembersRouteImport } from './routes/_app.p.$projectSlug.members'
import { Route as AppPProjectSlugFilesRouteImport } from './routes/_app.p.$projectSlug.files'
import { Route as AppPProjectSlugSSessionIdRouteImport } from './routes/_app.p.$projectSlug.s.$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPRoute = AppPRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => AppRoute,
} as any)
const AppPIndexRoute = AppPIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPRoute,
} as any)
const AppPProjectSlugRoute = AppPProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => AppPRoute,
} as any)
const AppPProjectSlugIndexRoute = AppPProjectSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPProjectSlugRoute,
} as any)
const AppPProjectSlugSkillsRoute = AppPProjectSlugSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppPProjectSlugRoute,
} as any)
const AppPProjectSlugSettingsRoute = AppPProjectSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppPProjectSlugRoute,
} as any)
const AppPProjectSlugScheduleRoute = AppPProjectSlugScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppPProjectSlugRoute,
} as any)
const AppPProjectSlugMembersRoute = AppPProjectSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppPProjectSlugRoute,
} as any)
const AppPProjectSlugFilesRoute = AppPProjectSlugFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppPProjectSlugRoute,
} as any)
const AppPProjectSlugSSessionIdRoute =
  AppPProjectSlugSSessionIdRouteImport.update({
    id: '/s/$sessionId',
    path: '/s/$sessionId',
    getParentRoute: () => AppPProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/p': typeof AppPRouteWithChildren
  '/p/$projectSlug': typeof AppPProjectSlugRouteWithChildren
  '/p/': typeof AppPIndexRoute
  '/p/$projectSlug/files': typeof AppPProjectSlugFilesRoute
  '/p/$projectSlug/members': typeof AppPProjectSlugMembersRoute
  '/p/$projectSlug/schedule': typeof AppPProjectSlugScheduleRoute
  '/p/$projectSlug/settings': typeof AppPProjectSlugSettingsRoute
  '/p/$projectSlug/skills': typeof AppPProjectSlugSkillsRoute
  '/p/$projectSlug/': typeof AppPProjectSlugIndexRoute
  '/p/$projectSlug/s/$sessionId': typeof AppPProjectSlugSSessionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/p': typeof AppPIndexRoute
  '/p/$projectSlug/files': typeof AppPProjectSlugFilesRoute
  '/p/$projectSlug/members': typeof AppPProjectSlugMembersRoute
  '/p/$projectSlug/schedule': typeof AppPProjectSlugScheduleRoute
  '/p/$projectSlug/settings': typeof AppPProjectSlugSettingsRoute
  '/p/$projectSlug/skills': typeof AppPProjectSlugSkillsRoute
  '/p/$projectSlug': typeof AppPProjectSlugIndexRoute
  '/p/$projectSlug/s/$sessionId': typeof AppPProjectSlugSSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/p': typeof AppPRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/p/$projectSlug': typeof AppPProjectSlugRouteWithChildren
  '/_app/p/': typeof AppPIndexRoute
  '/_app/p/$projectSlug/files': typeof AppPProjectSlugFilesRoute
  '/_app/p/$projectSlug/members': typeof AppPProjectSlugMembersRoute
  '/_app/p/$projectSlug/schedule': typeof AppPProjectSlugScheduleRoute
  '/_app/p/$projectSlug/settings': typeof AppPProjectSlugSettingsRoute
  '/_app/p/$projectSlug/skills': typeof AppPProjectSlugSkillsRoute
  '/_app/p/$projectSlug/': typeof AppPProjectSlugIndexRoute
  '/_app/p/$projectSlug/s/$sessionId': typeof AppPProjectSlugSSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/p'
    | '/p/$projectSlug'
    | '/p/'
    | '/p/$projectSlug/files'
    | '/p/$projectSlug/members'
    | '/p/$projectSlug/schedule'
    | '/p/$projectSlug/settings'
    | '/p/$projectSlug/skills'
    | '/p/$projectSlug/'
    | '/p/$projectSlug/s/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/p'
    | '/p/$projectSlug/files'
    | '/p/$projectSlug/members'
    | '/p/$projectSlug/schedule'
    | '/p/$projectSlug/settings'
    | '/p/$projectSlug/skills'
    | '/p/$projectSlug'
    | '/p/$projectSlug/s/$sessionId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/p'
    | '/_app/'
    | '/_app/p/$projectSlug'
    | '/_app/p/'
    | '/_app/p/$projectSlug/files'
    | '/_app/p/$projectSlug/members'
    | '/_app/p/$projectSlug/schedule'
    | '/_app/p/$projectSlug/settings'
    | '/_app/p/$projectSlug/skills'
    | '/_app/p/$projectSlug/'
    | '/_app/p/$projectSlug/s/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p': {
      id: '/_app/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof AppPRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/': {
      id: '/_app/p/'
      path: '/'
      fullPath: '/p/'
      preLoaderRoute: typeof AppPIndexRouteImport
      parentRoute: typeof AppPRoute
    }
    '/_app/p/$projectSlug': {
      id: '/_app/p/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/p/$projectSlug'
      preLoaderRoute: typeof AppPProjectSlugRouteImport
      parentRoute: typeof AppPRoute
    }
    '/_app/p/$projectSlug/': {
      id: '/_app/p/$projectSlug/'
      path: '/'
      fullPath: '/p/$projectSlug/'
      preLoaderRoute: typeof AppPProjectSlugIndexRouteImport
      parentRoute: typeof AppPProjectSlugRoute
    }
    '/_app/p/$projectSlug/skills': {
      id: '/_app/p/$projectSlug/skills'
      path: '/skills'
      fullPath: '/p/$projectSlug/skills'
      preLoaderRoute: typeof AppPProjectSlugSkillsRouteImport
      parentRoute: typeof AppPProjectSlugRoute
    }
    '/_app/p/$projectSlug/settings': {
      id: '/_app/p/$projectSlug/settings'
      path: '/settings'
      fullPath: '/p/$projectSlug/settings'
      preLoaderRoute: typeof AppPProjectSlugSettingsRouteImport
      parentRoute: typeof AppPProjectSlugRoute
    }
    '/_app/p/$projectSlug/schedule': {
      id: '/_app/p/$projectSlug/schedule'
      path: '/schedule'
      fullPath: '/p/$projectSlug/schedule'
      preLoaderRoute: typeof AppPProjectSlugScheduleRouteImport
      parentRoute: typeof AppPProjectSlugRoute
    }
    '/_app/p/$projectSlug/members': {
      id: '/_app/p/$projectSlug/members'
      path: '/members'
      fullPath: '/p/$projectSlug/members'
      preLoaderRoute: typeof AppPProjectSlugMembersRouteImport
      parentRoute: typeof AppPProjectSlugRoute
    }
    '/_app/p/$projectSlug/files': {
      id: '/_app/p/$projectSlug/files'
      path: '/files'
      fullPath: '/p/$projectSlug/files'
      preLoaderRoute: typeof AppPProjectSlugFilesRouteImport
      parentRoute: typeof AppPProjectSlugRoute
    }
    '/_app/p/$projectSlug/s/$sessionId': {
      id: '/_app/p/$projectSlug/s/$sessionId'
      path: '/s/$sessionId'
      fullPath: '/p/$projectSlug/s/$sessionId'
      preLoaderRoute: typeof AppPProjectSlugSSessionIdRouteImport
      parentRoute: typeof AppPProjectSlugRoute
    }
  }
}

interface AppPProjectSlugRouteChildren {
  AppPProjectSlugFilesRoute: typeof AppPProjectSlugFilesRoute
  AppPProjectSlugMembersRoute: typeof AppPProjectSlugMembersRoute
  AppPProjectSlugScheduleRoute: typeof AppPProjectSlugScheduleRoute
  AppPProjectSlugSettingsRoute: typeof AppPProjectSlugSettingsRoute
  AppPProjectSlugSkillsRoute: typeof AppPProjectSlugSkillsRoute
  AppPProjectSlugIndexRoute: typeof AppPProjectSlugIndexRoute
  AppPProjectSlugSSessionIdRoute: typeof AppPProjectSlugSSessionIdRoute
}

const AppPProjectSlugRouteChildren: AppPProjectSlugRouteChildren = {
  AppPProjectSlugFilesRoute: AppPProjectSlugFilesRoute,
  AppPProjectSlugMembersRoute: AppPProjectSlugMembersRoute,
  AppPProjectSlugScheduleRoute: AppPProjectSlugScheduleRoute,
  AppPProjectSlugSettingsRoute: AppPProjectSlugSettingsRoute,
  AppPProjectSlugSkillsRoute: AppPProjectSlugSkillsRoute,
  AppPProjectSlugIndexRoute: AppPProjectSlugIndexRoute,
  AppPProjectSlugSSessionIdRoute: AppPProjectSlugSSessionIdRoute,
}

const AppPProjectSlugRouteWithChildren = AppPProjectSlugRoute._addFileChildren(
  AppPProjectSlugRouteChildren,
)

interface AppPRouteChildren {
  AppPProjectSlugRoute: typeof AppPProjectSlugRouteWithChildren
  AppPIndexRoute: typeof AppPIndexRoute
}

const AppPRouteChildren: AppPRouteChildren = {
  AppPProjectSlugRoute: AppPProjectSlugRouteWithChildren,
  AppPIndexRoute: AppPIndexRoute,
}

const AppPRouteWithChildren = AppPRoute._addFileChildren(AppPRouteChildren)

interface AppRouteChildren {
  AppPRoute: typeof AppPRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPRoute: AppPRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
